// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package generator

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"burst.generateTime": {
			Default:     "1s",
			Description: "The amount of time the generator is generating records. Must be positive. If this option is empty, generator will generate records forever.",
			Type:        sdk.ParameterTypeDuration,
			Validations: []sdk.Validation{},
		},
		"burst.sleepTime": {
			Default:     "0s",
			Description: "The time the generator 'sleeps' before it starts generating records. Must be non-negative.",
			Type:        sdk.ParameterTypeDuration,
			Validations: []sdk.Validation{},
		},
		"collections.*.format.options.*": {
			Default:     "",
			Description: "The options for the format type selected, which are:   1. For raw and structured: pairs of field names and field types, where the type can be one of: int, string, time, bool.   2. For the file format: a path to the file.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"collections.*.format.options.path": {
			Default:     "",
			Description: "Path to the input file (only applicable if the format type is file).",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"collections.*.format.type": {
			Default:     "",
			Description: "The format of the generated payload data (raw, structured, file).",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"raw", "structured", "file"}},
			},
		},
		"collections.*.operation": {
			Default:     "created",
			Description: "The generated record operation.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
				sdk.ValidationInclusion{List: []string{"created", "updated", "deleted"}},
			},
		},
		"format.options.*": {
			Default:     "",
			Description: "The options for the format type selected, which are:   1. For raw and structured: pairs of field names and field types, where the type can be one of: int, string, time, bool.   2. For the file format: a path to the file.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"format.options.path": {
			Default:     "",
			Description: "Path to the input file (only applicable if the format type is file).",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"format.type": {
			Default:     "",
			Description: "The format of the generated payload data (raw, structured, file).",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"raw", "structured", "file"}},
			},
		},
		"operation": {
			Default:     "created",
			Description: "The generated record operation.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
				sdk.ValidationInclusion{List: []string{"created", "updated", "deleted"}},
			},
		},
		"readTime": {
			Default:     "0s",
			Description: "The time it takes to 'read' a record.",
			Type:        sdk.ParameterTypeDuration,
			Validations: []sdk.Validation{},
		},
		"recordCount": {
			Default:     "0",
			Description: "Number of records to be generated. -1 for no limit.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{},
		},
	}
}
